
export interface Country {
    code: string;
    name: string;
    flag: string;
    currencyCode?: string;
}

export const COUNTRIES: Country[] = [
    { code: "AF", name: "Afghanistan", flag: "🇦🇫", currencyCode: "AFN" },
    { code: "AX", name: "Åland Islands", flag: "🇦🇽", currencyCode: "EUR" },
    { code: "AL", name: "Albania", flag: "🇦🇱", currencyCode: "ALL" },
    { code: "DZ", name: "Algeria", flag: "🇩🇿", currencyCode: "DZD" },
    { code: "AS", name: "American Samoa", flag: "🇦🇸", currencyCode: "USD" },
    { code: "AD", name: "Andorra", flag: "🇦🇩", currencyCode: "EUR" },
    { code: "AO", name: "Angola", flag: "🇦🇴", currencyCode: "AOA" },
    { code: "AI", name: "Anguilla", flag: "🇦🇮", currencyCode: "XCD" },
    { code: "AQ", name: "Antarctica", flag: "🇦🇶" },
    { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", currencyCode: "XCD" },
    { code: "AR", name: "Argentina", flag: "🇦🇷", currencyCode: "ARS" },
    { code: "AM", name: "Armenia", flag: "🇦🇲", currencyCode: "AMD" },
    { code: "AW", name: "Aruba", flag: "🇦🇼", currencyCode: "AWG" },
    { code: "AU", name: "Australia", flag: "🇦🇺", currencyCode: "AUD" },
    { code: "AT", name: "Austria", flag: "🇦🇹", currencyCode: "EUR" },
    { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", currencyCode: "AZN" },
    { code: "BS", name: "Bahamas", flag: "🇧🇸", currencyCode: "BSD" },
    { code: "BH", name: "Bahrain", flag: "🇧🇭", currencyCode: "BHD" },
    { code: "BD", name: "Bangladesh", flag: "🇧🇩", currencyCode: "BDT" },
    { code: "BB", name: "Barbados", flag: "🇧🇧", currencyCode: "BBD" },
    { code: "BY", name: "Belarus", flag: "🇧🇾", currencyCode: "BYN" },
    { code: "BE", name: "Belgium", flag: "🇧🇪", currencyCode: "EUR" },
    { code: "BZ", name: "Belize", flag: "🇧🇿", currencyCode: "BZD" },
    { code: "BJ", name: "Benin", flag: "🇧🇯", currencyCode: "XOF" },
    { code: "BM", name: "Bermuda", flag: "🇧🇲", currencyCode: "BMD" },
    { code: "BT", name: "Bhutan", flag: "🇧🇹", currencyCode: "BTN" },
    { code: "BO", name: "Bolivia", flag: "🇧🇴", currencyCode: "BOB" },
    { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", flag: "🇧🇶", currencyCode: "USD" },
    { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", currencyCode: "BAM" },
    { code: "BW", name: "Botswana", flag: "🇧🇼", currencyCode: "BWP" },
    { code: "BV", name: "Bouvet Island", flag: "🇧🇻" },
    { code: "BR", name: "Brazil", flag: "🇧🇷", currencyCode: "BRL" },
    { code: "IO", name: "British Indian Ocean Territory", flag: "🇮🇴", currencyCode: "USD" },
    { code: "BN", name: "Brunei Darussalam", flag: "🇧🇳", currencyCode: "BND" },
    { code: "BG", name: "Bulgaria", flag: "🇧🇬", currencyCode: "BGN" },
    { code: "BF", name: "Burkina Faso", flag: "🇧🇫", currencyCode: "XOF" },
    { code: "BI", name: "Burundi", flag: "🇧🇮", currencyCode: "BIF" },
    { code: "CV", name: "Cabo Verde", flag: "🇨🇻", currencyCode: "CVE" },
    { code: "KH", name: "Cambodia", flag: "🇰🇭", currencyCode: "KHR" },
    { code: "CM", name: "Cameroon", flag: "🇨🇲", currencyCode: "XAF" },
    { code: "CA", name: "Canada", flag: "🇨🇦", currencyCode: "CAD" },
    { code: "KY", name: "Cayman Islands", flag: "🇰🇾", currencyCode: "KYD" },
    { code: "CF", name: "Central African Republic", flag: "🇨🇫", currencyCode: "XAF" },
    { code: "TD", name: "Chad", flag: "🇹🇩", currencyCode: "XAF" },
    { code: "CL", name: "Chile", flag: "🇨🇱", currencyCode: "CLP" },
    { code: "CN", name: "China", flag: "🇨🇳", currencyCode: "CNY" },
    { code: "CX", name: "Christmas Island", flag: "🇨🇽", currencyCode: "AUD" },
    { code: "CC", name: "Cocos (Keeling) Islands", flag: "🇨🇨", currencyCode: "AUD" },
    { code: "CO", name: "Colombia", flag: "🇨🇴", currencyCode: "COP" },
    { code: "KM", name: "Comoros", flag: "🇰🇲", currencyCode: "KMF" },
    { code: "CG", name: "Congo", flag: "🇨🇬", currencyCode: "XAF" },
    { code: "CD", name: "Congo, Democratic Republic of the", flag: "🇨🇩", currencyCode: "CDF" },
    { code: "CK", name: "Cook Islands", flag: "🇨🇰", currencyCode: "NZD" },
    { code: "CR", name: "Costa Rica", flag: "🇨🇷", currencyCode: "CRC" },
    { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮", currencyCode: "XOF" },
    { code: "HR", name: "Croatia", flag: "🇭🇷", currencyCode: "EUR" },
    { code: "CU", name: "Cuba", flag: "🇨🇺", currencyCode: "CUP" },
    { code: "CW", name: "Curaçao", flag: "🇨🇼", currencyCode: "ANG" },
    { code: "CY", name: "Cyprus", flag: "🇨🇾", currencyCode: "EUR" },
    { code: "CZ", name: "Czechia", flag: "🇨🇿", currencyCode: "CZK" },
    { code: "DK", name: "Denmark", flag: "🇩🇰", currencyCode: "DKK" },
    { code: "DJ", name: "Djibouti", flag: "🇩🇯", currencyCode: "DJF" },
    { code: "DM", name: "Dominica", flag: "🇩🇲", currencyCode: "XCD" },
    { code: "DO", name: "Dominican Republic", flag: "🇩🇴", currencyCode: "DOP" },
    { code: "EC", name: "Ecuador", flag: "🇪🇨", currencyCode: "USD" },
    { code: "EG", name: "Egypt", flag: "🇪🇬", currencyCode: "EGP" },
    { code: "SV", name: "El Salvador", flag: "🇸🇻", currencyCode: "USD" },
    { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", currencyCode: "XAF" },
    { code: "ER", name: "Eritrea", flag: "🇪🇷", currencyCode: "ERN" },
    { code: "EE", name: "Estonia", flag: "🇪🇪", currencyCode: "EUR" },
    { code: "SZ", name: "Eswatini", flag: "🇸🇿", currencyCode: "SZL" },
    { code: "ET", name: "Ethiopia", flag: "🇪🇹", currencyCode: "ETB" },
    { code: "FK", name: "Falkland Islands (Malvinas)", flag: "🇫🇰", currencyCode: "FKP" },
    { code: "FO", name: "Faroe Islands", flag: "🇫🇴", currencyCode: "DKK" },
    { code: "FJ", name: "Fiji", flag: "🇫🇯", currencyCode: "FJD" },
    { code: "FI", name: "Finland", flag: "🇫🇮", currencyCode: "EUR" },
    { code: "FR", name: "France", flag: "🇫🇷", currencyCode: "EUR" },
    { code: "GF", name: "French Guiana", flag: "🇬🇫", currencyCode: "EUR" },
    { code: "PF", name: "French Polynesia", flag: "🇵🇫", currencyCode: "XPF" },
    { code: "TF", name: "French Southern Territories", flag: "🇹🇫", currencyCode: "EUR" },
    { code: "GA", name: "Gabon", flag: "🇬🇦", currencyCode: "XAF" },
    { code: "GM", name: "Gambia", flag: "🇬🇲", currencyCode: "GMD" },
    { code: "GE", name: "Georgia", flag: "🇬🇪", currencyCode: "GEL" },
    { code: "DE", name: "Germany", flag: "🇩🇪", currencyCode: "EUR" },
    { code: "GH", name: "Ghana", flag: "🇬🇭", currencyCode: "GHS" },
    { code: "GI", name: "Gibraltar", flag: "🇬🇮", currencyCode: "GIP" },
    { code: "GR", name: "Greece", flag: "🇬🇷", currencyCode: "EUR" },
    { code: "GL", name: "Greenland", flag: "🇬🇱", currencyCode: "DKK" },
    { code: "GD", name: "Grenada", flag: "🇬🇩", currencyCode: "XCD" },
    { code: "GP", name: "Guadeloupe", flag: "🇬🇵", currencyCode: "EUR" },
    { code: "GU", name: "Guam", flag: "🇬🇺", currencyCode: "USD" },
    { code: "GT", name: "Guatemala", flag: "🇬🇹", currencyCode: "GTQ" },
    { code: "GG", name: "Guernsey", flag: "🇬🇬", currencyCode: "GBP" },
    { code: "GN", name: "Guinea", flag: "🇬🇳", currencyCode: "GNF" },
    { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", currencyCode: "XOF" },
    { code: "GY", name: "Guyana", flag: "🇬🇾", currencyCode: "GYD" },
    { code: "HT", name: "Haiti", flag: "🇭🇹", currencyCode: "HTG" },
    { code: "HM", name: "Heard Island and McDonald Islands", flag: "🇭🇲", currencyCode: "AUD" },
    { code: "VA", name: "Holy See", flag: "🇻🇦", currencyCode: "EUR" },
    { code: "HN", name: "Honduras", flag: "🇭🇳", currencyCode: "HNL" },
    { code: "HK", name: "Hong Kong", flag: "🇭🇰", currencyCode: "HKD" },
    { code: "HU", name: "Hungary", flag: "🇭🇺", currencyCode: "HUF" },
    { code: "IS", name: "Iceland", flag: "🇮🇸", currencyCode: "ISK" },
    { code: "IN", name: "India", flag: "🇮🇳", currencyCode: "INR" },
    { code: "ID", name: "Indonesia", flag: "🇮🇩", currencyCode: "IDR" },
    { code: "IR", name: "Iran", flag: "🇮🇷", currencyCode: "IRR" },
    { code: "IQ", name: "Iraq", flag: "🇮🇶", currencyCode: "IQD" },
    { code: "IE", name: "Ireland", flag: "🇮🇪", currencyCode: "EUR" },
    { code: "IM", name: "Isle of Man", flag: "🇮🇲", currencyCode: "GBP" },
    { code: "IL", name: "Israel", flag: "🇮🇱", currencyCode: "ILS" },
    { code: "IT", name: "Italy", flag: "🇮🇹", currencyCode: "EUR" },
    { code: "JM", name: "Jamaica", flag: "🇯🇲", currencyCode: "JMD" },
    { code: "JP", name: "Japan", flag: "🇯🇵", currencyCode: "JPY" },
    { code: "JE", name: "Jersey", flag: "🇯🇪", currencyCode: "GBP" },
    { code: "JO", name: "Jordan", flag: "🇯🇴", currencyCode: "JOD" },
    { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", currencyCode: "KZT" },
    { code: "KE", name: "Kenya", flag: "🇰🇪", currencyCode: "KES" },
    { code: "KI", name: "Kiribati", flag: "🇰🇮", currencyCode: "AUD" },
    { code: "KP", name: "Korea (North)", flag: "🇰🇵", currencyCode: "KPW" },
    { code: "KR", name: "Korea (South)", flag: "🇰🇷", currencyCode: "KRW" },
    { code: "KW", name: "Kuwait", flag: "🇰🇼", currencyCode: "KWD" },
    { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", currencyCode: "KGS" },
    { code: "LA", name: "Lao People's Democratic Republic", flag: "🇱🇦", currencyCode: "LAK" },
    { code: "LV", name: "Latvia", flag: "🇱🇻", currencyCode: "EUR" },
    { code: "LB", name: "Lebanon", flag: "🇱🇧", currencyCode: "LBP" },
    { code: "LS", name: "Lesotho", flag: "🇱🇸", currencyCode: "LSL" },
    { code: "LR", name: "Liberia", flag: "🇱🇷", currencyCode: "LRD" },
    { code: "LY", name: "Libya", flag: "🇱🇾", currencyCode: "LYD" },
    { code: "LI", name: "Liechtenstein", flag: "🇱🇮", currencyCode: "CHF" },
    { code: "LT", name: "Lithuania", flag: "🇱🇹", currencyCode: "EUR" },
    { code: "LU", name: "Luxembourg", flag: "🇱🇺", currencyCode: "EUR" },
    { code: "MO", name: "Macao", flag: "🇲🇴", currencyCode: "MOP" },
    { code: "MG", name: "Madagascar", flag: "🇲🇬", currencyCode: "MGA" },
    { code: "MW", name: "Malawi", flag: "🇲🇼", currencyCode: "MWK" },
    { code: "MY", name: "Malaysia", flag: "🇲🇾", currencyCode: "MYR" },
    { code: "MV", name: "Maldives", flag: "🇲🇻", currencyCode: "MVR" },
    { code: "ML", name: "Mali", flag: "🇲🇱", currencyCode: "XOF" },
    { code: "MT", name: "Malta", flag: "🇲🇹", currencyCode: "EUR" },
    { code: "MH", name: "Marshall Islands", flag: "🇲🇭", currencyCode: "USD" },
    { code: "MQ", name: "Martinique", flag: "🇲🇶", currencyCode: "EUR" },
    { code: "MR", name: "Mauritania", flag: "🇲🇷", currencyCode: "MRU" },
    { code: "MU", name: "Mauritius", flag: "🇲🇺", currencyCode: "MUR" },
    { code: "YT", name: "Mayotte", flag: "🇾🇹", currencyCode: "EUR" },
    { code: "MX", name: "Mexico", flag: "🇲🇽", currencyCode: "MXN" },
    { code: "FM", name: "Micronesia (Federated States of)", flag: "🇫🇲", currencyCode: "USD" },
    { code: "MD", name: "Moldova", flag: "🇲🇩", currencyCode: "MDL" },
    { code: "MC", name: "Monaco", flag: "🇲🇨", currencyCode: "EUR" },
    { code: "MN", name: "Mongolia", flag: "🇲🇳", currencyCode: "MNT" },
    { code: "ME", name: "Montenegro", flag: "🇲🇪", currencyCode: "EUR" },
    { code: "MS", name: "Montserrat", flag: "🇲🇸", currencyCode: "XCD" },
    { code: "MA", name: "Morocco", flag: "🇲🇦", currencyCode: "MAD" },
    { code: "MZ", name: "Mozambique", flag: "🇲🇿", currencyCode: "MZN" },
    { code: "MM", name: "Myanmar", flag: "🇲🇲", currencyCode: "MMK" },
    { code: "NA", name: "Namibia", flag: "🇳🇦", currencyCode: "NAD" },
    { code: "NR", name: "Nauru", flag: "🇳🇷", currencyCode: "AUD" },
    { code: "NP", name: "Nepal", flag: "🇳🇵", currencyCode: "NPR" },
    { code: "NL", name: "Netherlands", flag: "🇳🇱", currencyCode: "EUR" },
    { code: "NC", name: "New Caledonia", flag: "🇳🇨", currencyCode: "XPF" },
    { code: "NZ", name: "New Zealand", flag: "🇳🇿", currencyCode: "NZD" },
    { code: "NI", name: "Nicaragua", flag: "🇳🇮", currencyCode: "NIO" },
    { code: "NE", name: "Niger", flag: "🇳🇪", currencyCode: "XOF" },
    { code: "NG", name: "Nigeria", flag: "🇳🇬", currencyCode: "NGN" },
    { code: "NU", name: "Niue", flag: "🇳🇺", currencyCode: "NZD" },
    { code: "NF", name: "Norfolk Island", flag: "🇳🇫", currencyCode: "AUD" },
    { code: "MK", name: "North Macedonia", flag: "🇲🇰", currencyCode: "MKD" },
    { code: "MP", name: "Northern Mariana Islands", flag: "🇲🇵", currencyCode: "USD" },
    { code: "NO", name: "Norway", flag: "🇳🇴", currencyCode: "NOK" },
    { code: "OM", name: "Oman", flag: "🇴🇲", currencyCode: "OMR" },
    { code: "PK", name: "Pakistan", flag: "🇵🇰", currencyCode: "PKR" },
    { code: "PW", name: "Palau", flag: "🇵🇼", currencyCode: "USD" },
    { code: "PS", name: "Palestine, State of", flag: "🇵🇸", currencyCode: "ILS" },
    { code: "PA", name: "Panama", flag: "🇵🇦", currencyCode: "PAB" },
    { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", currencyCode: "PGK" },
    { code: "PY", name: "Paraguay", flag: "🇵🇾", currencyCode: "PYG" },
    { code: "PE", name: "Peru", flag: "🇵🇪", currencyCode: "PEN" },
    { code: "PH", name: "Philippines", flag: "🇵🇭", currencyCode: "PHP" },
    { code: "PN", name: "Pitcairn", flag: "🇵🇳", currencyCode: "NZD" },
    { code: "PL", name: "Poland", flag: "🇵🇱", currencyCode: "PLN" },
    { code: "PT", name: "Portugal", flag: "🇵🇹", currencyCode: "EUR" },
    { code: "PR", name: "Puerto Rico", flag: "🇵🇷", currencyCode: "USD" },
    { code: "QA", name: "Qatar", flag: "🇶🇦", currencyCode: "QAR" },
    { code: "RE", name: "Réunion", flag: "🇷🇪", currencyCode: "EUR" },
    { code: "RO", name: "Romania", flag: "🇷🇴", currencyCode: "RON" },
    { code: "RU", name: "Russian Federation", flag: "🇷🇺", currencyCode: "RUB" },
    { code: "RW", name: "Rwanda", flag: "🇷🇼", currencyCode: "RWF" },
    { code: "BL", name: "Saint Barthélemy", flag: "🇧🇱", currencyCode: "EUR" },
    { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", flag: "🇸🇭", currencyCode: "SHP" },
    { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", currencyCode: "XCD" },
    { code: "LC", name: "Saint Lucia", flag: "🇱🇨", currencyCode: "XCD" },
    { code: "MF", name: "Saint Martin (French part)", flag: "🇲🇫", currencyCode: "EUR" },
    { code: "PM", name: "Saint Pierre and Miquelon", flag: "🇵🇲", currencyCode: "EUR" },
    { code: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", currencyCode: "XCD" },
    { code: "WS", name: "Samoa", flag: "🇼🇸", currencyCode: "WST" },
    { code: "SM", name: "San Marino", flag: "🇸🇲", currencyCode: "EUR" },
    { code: "ST", name: "Sao Tome and Principe", flag: "🇸🇹", currencyCode: "STN" },
    { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", currencyCode: "SAR" },
    { code: "SN", name: "Senegal", flag: "🇸🇳", currencyCode: "XOF" },
    { code: "RS", name: "Serbia", flag: "🇷🇸", currencyCode: "RSD" },
    { code: "SC", name: "Seychelles", flag: "🇸🇨", currencyCode: "SCR" },
    { code: "SL", name: "Sierra Leone", flag: "🇸🇱", currencyCode: "SLL" },
    { code: "SG", name: "Singapore", flag: "🇸🇬", currencyCode: "SGD" },
    { code: "SX", name: "Sint Maarten (Dutch part)", flag: "🇸🇽", currencyCode: "ANG" },
    { code: "SK", name: "Slovakia", flag: "🇸🇰", currencyCode: "EUR" },
    { code: "SI", name: "Slovenia", flag: "🇸🇮", currencyCode: "EUR" },
    { code: "SB", name: "Solomon Islands", flag: "🇸🇧", currencyCode: "SBD" },
    { code: "SO", name: "Somalia", flag: "🇸🇴", currencyCode: "SOS" },
    { code: "ZA", name: "South Africa", flag: "🇿🇦", currencyCode: "ZAR" },
    { code: "GS", name: "South Georgia and the South Sandwich Islands", flag: "🇬🇸", currencyCode: "GBP" },
    { code: "SS", name: "South Sudan", flag: "🇸🇸", currencyCode: "SSP" },
    { code: "ES", name: "Spain", flag: "🇪🇸", currencyCode: "EUR" },
    { code: "LK", name: "Sri Lanka", flag: "🇱🇰", currencyCode: "LKR" },
    { code: "SD", name: "Sudan", flag: "🇸🇩", currencyCode: "SDG" },
    { code: "SR", name: "Suriname", flag: "🇸🇷", currencyCode: "SRD" },
    { code: "SJ", name: "Svalbard and Jan Mayen", flag: "🇸🇯", currencyCode: "NOK" },
    { code: "SE", name: "Sweden", flag: "🇸🇪", currencyCode: "SEK" },
    { code: "CH", name: "Switzerland", flag: "🇨🇭", currencyCode: "CHF" },
    { code: "SY", name: "Syrian Arab Republic", flag: "🇸🇾", currencyCode: "SYP" },
    { code: "TW", name: "Taiwan, Province of China", flag: "🇹🇼", currencyCode: "TWD" },
    { code: "TJ", name: "Tajikistan", flag: "🇹🇯", currencyCode: "TJS" },
    { code: "TZ", name: "Tanzania, United Republic of", flag: "🇹🇿", currencyCode: "TZS" },
    { code: "TH", name: "Thailand", flag: "🇹🇭", currencyCode: "THB" },
    { code: "TL", name: "Timor-Leste", flag: "🇹🇱", currencyCode: "USD" },
    { code: "TG", name: "Togo", flag: "🇹🇬", currencyCode: "XOF" },
    { code: "TK", name: "Tokelau", flag: "🇹🇰", currencyCode: "NZD" },
    { code: "TO", name: "Tonga", flag: "🇹🇴", currencyCode: "TOP" },
    { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", currencyCode: "TTD" },
    { code: "TN", name: "Tunisia", flag: "🇹🇳", currencyCode: "TND" },
    { code: "TR", name: "Turkey", flag: "🇹🇷", currencyCode: "TRY" },
    { code: "TM", name: "Turkmenistan", flag: "🇹🇲", currencyCode: "TMT" },
    { code: "TC", name: "Turks and Caicos Islands", flag: "🇹🇨", currencyCode: "USD" },
    { code: "TV", name: "Tuvalu", flag: "🇹🇻", currencyCode: "TVD" },
    { code: "UG", name: "Uganda", flag: "🇺🇬", currencyCode: "UGX" },
    { code: "UA", name: "Ukraine", flag: "🇺🇦", currencyCode: "UAH" },
    { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", currencyCode: "AED" },
    { code: "GB", name: "United Kingdom", flag: "🇬🇧", currencyCode: "GBP" },
    { code: "US", name: "United States of America", flag: "🇺🇸", currencyCode: "USD" },
    { code: "UM", name: "United States Minor Outlying Islands", flag: "🇺🇲", currencyCode: "USD" },
    { code: "UY", name: "Uruguay", flag: "🇺🇾", currencyCode: "UYU" },
    { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", currencyCode: "UZS" },
    { code: "VU", name: "Vanuatu", flag: "🇻🇺", currencyCode: "VUV" },
    { code: "VE", name: "Venezuela (Bolivarian Republic of)", flag: "🇻🇪", currencyCode: "VES" },
    { code: "VN", name: "Viet Nam", flag: "🇻🇳", currencyCode: "VND" },
    { code: "VG", name: "Virgin Islands (British)", flag: "🇻🇬", currencyCode: "USD" },
    { code: "VI", name: "Virgin Islands (U.S.)", flag: "🇻🇮", currencyCode: "USD" },
    { code: "WF", name: "Wallis and Futuna", flag: "🇼🇫", currencyCode: "XPF" },
    { code: "EH", name: "Western Sahara", flag: "🇪🇭", currencyCode: "MAD" },
    { code: "YE", name: "Yemen", flag: "🇾🇪", currencyCode: "YER" },
    { code: "ZM", name: "Zambia", flag: "🇿🇲", currencyCode: "ZMW" },
    { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", currencyCode: "ZWL" }
].sort((a, b) => a.name.localeCompare(b.name));
