export interface Currency {
    code: string;
    name: string;
    symbol: string;
    flag?: string;
}

export const CURRENCIES: Currency[] = [
    { code: "AFN", name: "Afghan Afghani", symbol: "؋", flag: "🇦🇫" },
    { code: "ALL", name: "Albanian Lek", symbol: "L", flag: "🇦🇱" },
    { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", flag: "🇩🇿" },
    { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", flag: "🇦🇴" },
    { code: "ARS", name: "Argentine Peso", symbol: "$", flag: "🇦🇷" },
    { code: "AMD", name: "Armenian Dram", symbol: "֏", flag: "🇦🇲" },
    { code: "AWG", name: "Aruban Florin", symbol: "ƒ", flag: "🇦🇼" },
    { code: "AUD", name: "Australian Dollar", symbol: "A$", flag: "🇦🇺" },
    { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", flag: "🇦🇿" },
    { code: "BSD", name: "Bahamian Dollar", symbol: "$", flag: "🇧🇸" },
    { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", flag: "🇧🇭" },
    { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", flag: "🇧🇩" },
    { code: "BBD", name: "Barbadian Dollar", symbol: "$", flag: "🇧🇧" },
    { code: "BYN", name: "Belarusian Ruble", symbol: "Br", flag: "🇧🇾" },
    { code: "BZD", name: "Belize Dollar", symbol: "BZ$", flag: "🇧🇿" },
    { code: "BMD", name: "Bermudian Dollar", symbol: "$", flag: "🇧🇲" },
    { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", flag: "🇧🇹" },
    { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", flag: "🇧🇴" },
    { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM", flag: "🇧🇦" },
    { code: "BWP", name: "Botswanan Pula", symbol: "P", flag: "🇧🇼" },
    { code: "BRL", name: "Brazilian Real", symbol: "R$", flag: "🇧🇷" },
    { code: "BND", name: "Brunei Dollar", symbol: "$", flag: "🇧🇳" },
    { code: "BGN", name: "Bulgarian Lev", symbol: "лв", flag: "🇧🇬" },
    { code: "BIF", name: "Burundian Franc", symbol: "FBu", flag: "🇧🇮" },
    { code: "KHR", name: "Cambodian Riel", symbol: "៛", flag: "🇰🇭" },
    { code: "CAD", name: "Canadian Dollar", symbol: "CA$", flag: "🇨🇦" },
    { code: "CVE", name: "Cape Verdean Escudo", symbol: "Esc", flag: "🇨🇻" },
    { code: "KYD", name: "Cayman Islands Dollar", symbol: "$", flag: "🇰🇾" },
    { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA", flag: "🇨🇫" },
    { code: "XPF", name: "CFP Franc", symbol: "₣", flag: "🇵🇫" },
    { code: "CLP", name: "Chilean Peso", symbol: "$", flag: "🇨🇱" },
    { code: "CNY", name: "Chinese Yuan", symbol: "¥", flag: "🇨🇳" },
    { code: "COP", name: "Colombian Peso", symbol: "$", flag: "🇨🇴" },
    { code: "KMF", name: "Comorian Franc", symbol: "CF", flag: "🇰🇲" },
    { code: "CDF", name: "Congolese Franc", symbol: "FC", flag: "🇨🇩" },
    { code: "CRC", name: "Costa Rican Colón", symbol: "₡", flag: "🇨🇷" },
    { code: "HRK", name: "Croatian Kuna", symbol: "kn", flag: "🇭🇷" },
    { code: "CUP", name: "Cuban Peso", symbol: "$", flag: "🇨🇺" },
    { code: "CZK", name: "Czech Koruna", symbol: "Kč", flag: "🇨🇿" },
    { code: "DKK", name: "Danish Krone", symbol: "kr", flag: "🇩🇰" },
    { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", flag: "🇩🇯" },
    { code: "DOP", name: "Dominican Peso", symbol: "RD$", flag: "🇩🇴" },
    { code: "XCD", name: "East Caribbean Dollar", symbol: "$", flag: "🇦🇬" },
    { code: "EGP", name: "Egyptian Pound", symbol: "E£", flag: "🇪🇬" },
    { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", flag: "🇪🇷" },
    { code: "ETB", name: "Ethiopian Birr", symbol: "Br", flag: "🇪🇹" },
    { code: "EUR", name: "Euro", symbol: "€", flag: "🇪🇺" },
    { code: "FKP", name: "Falkland Islands Pound", symbol: "£", flag: "🇫🇰" },
    { code: "FJD", name: "Fijian Dollar", symbol: "$", flag: "🇫🇯" },
    { code: "GMD", name: "Gambian Dalasi", symbol: "D", flag: "🇬🇲" },
    { code: "GEL", name: "Georgian Lari", symbol: "₾", flag: "🇬🇪" },
    { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", flag: "🇬🇭" },
    { code: "GIP", name: "Gibraltar Pound", symbol: "£", flag: "🇬🇮" },
    { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", flag: "🇬🇹" },
    { code: "GNF", name: "Guinean Franc", symbol: "FG", flag: "🇬🇳" },
    { code: "GYD", name: "Guyanese Dollar", symbol: "$", flag: "🇬🇾" },
    { code: "HTG", name: "Haitian Gourde", symbol: "G", flag: "🇭🇹" },
    { code: "HNL", name: "Honduran Lempira", symbol: "L", flag: "🇭🇳" },
    { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", flag: "🇭🇰" },
    { code: "HUF", name: "Hungarian Forint", symbol: "Ft", flag: "🇭🇺" },
    { code: "ISK", name: "Icelandic Króna", symbol: "kr", flag: "🇮🇸" },
    { code: "INR", name: "Indian Rupee", symbol: "₹", flag: "🇮🇳" },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", flag: "🇮🇩" },
    { code: "IRR", name: "Iranian Rial", symbol: "﷼", flag: "🇮🇷" },
    { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", flag: "🇮🇶" },
    { code: "ILS", name: "Israeli New Shekel", symbol: "₪", flag: "🇮🇱" },
    { code: "JMD", name: "Jamaican Dollar", symbol: "$", flag: "🇯🇲" },
    { code: "JPY", name: "Japanese Yen", symbol: "¥", flag: "🇯🇵" },
    { code: "JOD", name: "Jordanian Dinar", symbol: "JD", flag: "🇯🇴" },
    { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", flag: "🇰🇿" },
    { code: "KES", name: "Kenyan Shilling", symbol: "KSh", flag: "🇰🇪" },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "KD", flag: "🇰🇼" },
    { code: "KGS", name: "Kyrgystani Som", symbol: "с", flag: "🇰🇬" },
    { code: "LAK", name: "Laotian Kip", symbol: "₭", flag: "🇱🇦" },
    { code: "LBP", name: "Lebanese Pound", symbol: "LL", flag: "🇱🇧" },
    { code: "LSL", name: "Lesotho Loti", symbol: "L", flag: "🇱🇸" },
    { code: "LRD", name: "Liberian Dollar", symbol: "$", flag: "🇱🇷" },
    { code: "LYD", name: "Libyan Dinar", symbol: "LD", flag: "🇱🇾" },
    { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", flag: "🇲🇴" },
    { code: "MKD", name: "Macedonian Denar", symbol: "ден", flag: "🇲🇰" },
    { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", flag: "🇲🇬" },
    { code: "MWK", name: "Malawian Kwacha", symbol: "MK", flag: "🇲🇼" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", flag: "🇲🇾" },
    { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", flag: "🇲🇻" },
    { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", flag: "🇲🇷" },
    { code: "MUR", name: "Mauritian Rupee", symbol: "₨", flag: "🇲🇺" },
    { code: "MXN", name: "Mexican Peso", symbol: "$", flag: "🇲🇽" },
    { code: "MDL", name: "Moldovan Leu", symbol: "L", flag: "🇲🇩" },
    { code: "MNT", name: "Mongolian Tugrik", symbol: "₮", flag: "🇲🇳" },
    { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", flag: "🇲🇦" },
    { code: "MZN", name: "Mozambican Metical", symbol: "MT", flag: "🇲🇿" },
    { code: "MMK", name: "Myanmar Kyat", symbol: "Ks", flag: "🇲🇲" },
    { code: "NAD", name: "Namibian Dollar", symbol: "$", flag: "🇳🇦" },
    { code: "NPR", name: "Nepalese Rupee", symbol: "₨", flag: "🇳🇵" },
    { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", flag: "🇨🇼" },
    { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", flag: "🇹🇼" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", flag: "🇳🇿" },
    { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", flag: "🇳🇮" },
    { code: "NGN", name: "Nigerian Naira", symbol: "₦", flag: "🇳🇬" },
    { code: "KPW", name: "North Korean Won", symbol: "₩", flag: "🇰🇵" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr", flag: "🇳🇴" },
    { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", flag: "🇴🇲" },
    { code: "PKR", name: "Pakistani Rupee", symbol: "₨", flag: "🇵🇰" },
    { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", flag: "🇵🇦" },
    { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", flag: "🇵🇬" },
    { code: "PYG", name: "Paraguayan Guarani", symbol: "₲", flag: "🇵🇾" },
    { code: "PEN", name: "Peruvian Sol", symbol: "S/.", flag: "🇵🇪" },
    { code: "PHP", name: "Philippine Peso", symbol: "₱", flag: "🇵🇭" },
    { code: "PLN", name: "Polish Zloty", symbol: "zł", flag: "🇵🇱" },
    { code: "QAR", name: "Qatari Rial", symbol: "ر.ق", flag: "🇶🇦" },
    { code: "RON", name: "Romanian Leu", symbol: "lei", flag: "🇷🇴" },
    { code: "RUB", name: "Russian Ruble", symbol: "₽", flag: "🇷🇺" },
    { code: "RWF", name: "Rwandan Franc", symbol: "RF", flag: "🇷🇼" },
    { code: "SHP", name: "Saint Helena Pound", symbol: "£", flag: "🇸🇭" },
    { code: "WST", name: "Samoan Tala", symbol: "T", flag: "🇼🇸" },
    { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db", flag: "🇸🇹" },
    { code: "SAR", name: "Saudi Riyal", symbol: "ر.س", flag: "🇸🇦" },
    { code: "RSD", name: "Serbian Dinar", symbol: "дин.", flag: "🇷🇸" },
    { code: "SCR", name: "Seychellois Rupee", symbol: "₨", flag: "🇸🇨" },
    { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le", flag: "🇸🇱" },
    { code: "SGD", name: "Singapore Dollar", symbol: "S$", flag: "🇸🇬" },
    { code: "SBD", name: "Solomon Islands Dollar", symbol: "$", flag: "🇸🇧" },
    { code: "SOS", name: "Somali Shilling", symbol: "S", flag: "🇸🇴" },
    { code: "ZAR", name: "South African Rand", symbol: "R", flag: "🇿🇦" },
    { code: "KRW", name: "South Korean Won", symbol: "₩", flag: "🇰🇷" },
    { code: "SSP", name: "South Sudanese Pound", symbol: "£", flag: "🇸🇸" },
    { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨", flag: "🇱🇰" },
    { code: "SDG", name: "Sudanese Pound", symbol: "ج.س.", flag: "🇸🇩" },
    { code: "SRD", name: "Surinamese Dollar", symbol: "$", flag: "🇸🇷" },
    { code: "SZL", name: "Swazi Lilangeni", symbol: "L", flag: "🇸🇿" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr", flag: "🇸🇪" },
    { code: "CHF", name: "Swiss Franc", symbol: "Fr", flag: "🇨🇭" },
    { code: "SYP", name: "Syrian Pound", symbol: "£", flag: "🇸🇾" },
    { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", flag: "🇹🇯" },
    { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", flag: "🇹🇿" },
    { code: "THB", name: "Thai Baht", symbol: "฿", flag: "🇹🇭" },
    { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", flag: "🇹🇴" },
    { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$", flag: "🇹🇹" },
    { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", flag: "🇹🇳" },
    { code: "TRY", name: "Turkish Lira", symbol: "₺", flag: "🇹🇷" },
    { code: "TMT", name: "Turkmenistani Manat", symbol: "T", flag: "🇹🇲" },
    { code: "UGX", name: "Ugandan Shilling", symbol: "USh", flag: "🇺🇬" },
    { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", flag: "🇺🇦" },
    { code: "AED", name: "United Arab Emirates Dirham", symbol: "د.إ", flag: "🇦🇪" },
    { code: "GBP", name: "United Kingdom Pound Sterling", symbol: "£", flag: "🇬🇧" },
    { code: "USD", name: "United States Dollar", symbol: "$", flag: "🇺🇸" },
    { code: "UYU", name: "Uruguayan Peso", symbol: "$U", flag: "🇺🇾" },
    { code: "UZS", name: "Uzbekistani Som", symbol: "лв", flag: "🇺🇿" },
    { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", flag: "🇻🇺" },
    { code: "VES", name: "Venezuelan Bolívar Soberano", symbol: "Bs.S", flag: "🇻🇪" },
    { code: "VND", name: "Vietnamese Dong", symbol: "₫", flag: "🇻🇳" },
    { code: "XOF", name: "West African CFA Franc", symbol: "CFA", flag: "🇧🇪" },
    { code: "YER", name: "Yemeni Rial", symbol: "﷼", flag: "🇾🇪" },
    { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", flag: "🇿🇲" },
    { code: "ZWL", name: "Zimbabwean Dollar", symbol: "$", flag: "🇿🇼" },
].sort((a, b) => a.name.localeCompare(b.name));
