"use client"

import { useEffect, useState } from "react"
import { useRouter, useParams } from "next/navigation"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import {
    Loader2,
    ArrowLeft,
    ShieldAlert,
    User,
    Activity,
    FileJson,
    Printer,
    FileText
} from "lucide-react"

interface AuditLog {
    event_id: string
    timestamp: string
    actor: {
        id?: string
        email: string
        role: string
        ip?: string
        user_agent?: string
    }
    action: {
        type: string
        description: string
    }
    severity: 'INFO' | 'WARNING' | 'CRITICAL'
    status: string
    metadata?: any
}

export default function AuditLogDetailPage() {
    const router = useRouter()
    const { id } = useParams()
    const [log, setLog] = useState<AuditLog | null>(null)
    const [loading, setLoading] = useState(true)

    const handlePrint = () => {
        window.print();
    }

    const handleDownloadTxt = () => {
        if (!log) return;

        const text = `
BIZED AUDIT LOG REPORT
----------------------
Event ID: ${log.event_id}
Timestamp: ${new Date(log.timestamp).toLocaleString()}
Severity: ${log.severity}
Status: ${log.status}

ACTOR IDENTITY
--------------
Email: ${log.actor.email}
Role: ${log.actor.role}
User ID: ${log.actor.id || 'N/A'}
IP Address: ${log.actor.ip || '0.0.0.0'}
User Agent: ${log.actor.user_agent || 'N/A'}

ACTION CONTEXT
--------------
Type: ${log.action.type}
Description: ${log.action.description}

RAW METADATA
------------
${JSON.stringify(log, null, 2)}

----------------------
Generated by Bized Security Engine
`.trim();

        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `audit-log-${log.event_id}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    useEffect(() => {
        const fetchLog = async () => {
            try {
                // Since the list API returns data, we search for the specific log or create a specific ID endpoint
                // For now, we fetch from the main API and filter, or we should have a specific endpoint.
                // Let's assume there is an API for single log or we fetch it.
                const res = await fetch(`/api/admin/audit?search=${id}`)
                if (res.ok) {
                    const json = await res.json()
                    const found = json.data.find((l: AuditLog) => l.event_id === id)
                    setLog(found || null)
                }
            } catch (error) {
                console.error("Failed to fetch audit log detail", error)
            } finally {
                setLoading(false)
            }
        }

        if (id) fetchLog()
    }, [id])

    if (loading) {
        return (
            <div className="flex items-center justify-center min-h-[400px]">
                <Loader2 className="animate-spin h-8 w-8 text-muted-foreground" />
            </div>
        )
    }

    if (!log) {
        return (
            <div className="space-y-4">
                <Button variant="ghost" onClick={() => router.back()} className="gap-2">
                    <ArrowLeft className="w-4 h-4" /> Back to Logs
                </Button>
                <div className="text-center py-12">
                    <h3 className="text-lg font-semibold">Log entry not found</h3>
                    <p className="text-muted-foreground">The requested audit log does not exist or has expired.</p>
                </div>
            </div>
        )
    }

    return (
        <div className="space-y-6 max-w-5xl mx-auto print:max-w-none print:p-0 print:space-y-8">
            <style jsx global>{`
                @media print {
                    @page {
                        margin: 15mm !important;
                        size: auto;
                    }
                    .no-print {
                        display: none !important;
                    }
                    body {
                        background: white !important;
                        padding: 0 !important;
                        color: #111 !important;
                        font-family: 'Inter', system-ui, sans-serif !important;
                        -webkit-print-color-adjust: exact !important;
                        print-color-adjust: exact !important;
                    }
                    .print-card {
                        break-inside: avoid !important;
                        page-break-inside: avoid !important;
                        border: 1px solid #e4e4e7 !important;
                        border-radius: 8px !important;
                        margin-bottom: 24px !important;
                        display: block !important;
                        width: 100% !important;
                    }
                    .print-header {
                        background-color: #f9fafb !important;
                        border-bottom: 1px solid #e4e4e7 !important;
                        padding: 12px 16px !important;
                    }
                    pre {
                        font-size: 9px !important;
                        line-height: 1.4 !important;
                        background: #ffffff !important;
                        color: #374151 !important;
                        border: 1px solid #f3f4f6 !important;
                        padding: 16px !important;
                        margin: 0 !important;
                        border-radius: 0 0 8px 8px !important;
                        white-space: pre-wrap !important;
                        word-wrap: break-word !important;
                    }
                }
            `}</style>

            <div className="flex items-center justify-between no-print">
                <Button variant="ghost" onClick={() => router.back()} className="gap-2">
                    <ArrowLeft className="w-4 h-4" /> Back to Logs
                </Button>
                <div className="flex items-center gap-2">
                    <Button variant="outline" size="sm" onClick={handleDownloadTxt} className="gap-2">
                        <FileText className="w-4 h-4" /> Download as Text
                    </Button>
                    <Button variant="outline" size="sm" onClick={handlePrint} className="gap-2">
                        <Printer className="w-4 h-4" /> Print to PDF
                    </Button>
                    <Badge variant={log.severity === 'CRITICAL' ? 'destructive' : 'outline'}>
                        {log.severity} SEVERITY
                    </Badge>
                </div>
            </div>

            {/* Professional Print Header */}
            <div className="hidden print:flex items-center justify-between border-b-4 border-zinc-900 pb-6 mb-8">
                <div className="flex items-center gap-4">
                    <div className="h-12 w-12 bg-zinc-900 rounded-lg flex items-center justify-center text-white font-bold text-xl">B</div>
                    <div>
                        <h1 className="text-2xl font-black tracking-tighter text-zinc-900">BIZED AUDIT REPORT</h1>
                        <p className="text-xs font-bold text-zinc-500 uppercase tracking-widest">Enterprise Security & Compliance Operations</p>
                    </div>
                </div>
                <div className="text-right flex flex-col items-end gap-1">
                    <Badge variant="outline" className="text-[10px] font-mono border-zinc-400 text-zinc-600 px-2 py-0">ID: {log.event_id}</Badge>
                    <p className="text-[10px] text-zinc-400 font-medium">DOCUMENT VERIFIED • {new Date().toLocaleDateString()}</p>
                </div>
            </div>

            <div className="flex items-end justify-between border-b pb-6 print:border-zinc-200">
                <div>
                    <h2 className="text-3xl font-bold tracking-tight print:text-2xl print:text-zinc-900">Event Analysis</h2>
                    <p className="text-muted-foreground font-mono text-sm mt-1 print:text-xs">Security Sequence: {log.event_id}</p>
                </div>
                <div className="text-right print:text-zinc-700">
                    <p className="text-sm font-semibold">{new Date(log.timestamp).toLocaleDateString('en-US', { dateStyle: 'long' })}</p>
                    <p className="text-sm text-muted-foreground font-mono">{new Date(log.timestamp).toLocaleTimeString()}</p>
                </div>
            </div>

            <div className="grid gap-6 md:grid-cols-2 print:grid-cols-1 print:gap-0">
                {/* Actor Card */}
                <Card className="overflow-hidden border-zinc-200 dark:border-zinc-800 print:print-card">
                    <CardHeader className="bg-muted/30 pb-3 flex flex-row items-center gap-2 print:print-header">
                        <User className="w-4 h-4 text-zinc-500" />
                        <CardTitle className="text-base font-bold print:text-sm">Originating Actor</CardTitle>
                    </CardHeader>
                    <CardContent className="pt-6 space-y-4">
                        <div className="flex justify-between items-center text-sm">
                            <span className="text-muted-foreground">Email Address</span>
                            <span className="font-semibold">{log.actor.email}</span>
                        </div>
                        <div className="flex justify-between items-center text-sm">
                            <span className="text-muted-foreground">System Role</span>
                            <Badge variant="secondary" className="uppercase text-[10px]">{log.actor.role}</Badge>
                        </div>
                        <div className="flex justify-between items-center text-sm">
                            <span className="text-muted-foreground font-mono text-[10px] uppercase">User ID</span>
                            <span className="font-mono text-xs truncate max-w-[200px]">{log.actor.id || 'N/A'}</span>
                        </div>
                        <div className="flex justify-between items-center text-sm">
                            <span className="text-muted-foreground font-mono text-[10px] uppercase">IP Address</span>
                            <span className="font-mono text-xs">{log.actor.ip || '0.0.0.0'}</span>
                        </div>
                        <div className="space-y-1">
                            <span className="text-muted-foreground font-mono text-[10px] uppercase">User Agent</span>
                            <p className="font-mono text-[10px] text-zinc-500 line-clamp-2 leading-tight">
                                {log.actor.user_agent || 'Mozilla/5.0 (Unknown)'}
                            </p>
                        </div>
                    </CardContent>
                </Card>

                {/* Action Card */}
                <Card className="overflow-hidden border-zinc-200 dark:border-zinc-800 print:print-card">
                    <CardHeader className="bg-muted/30 pb-3 flex flex-row items-center gap-2 print:bg-zinc-50 print:border-b">
                        <Activity className="w-4 h-4 text-primary print:text-black" />
                        <CardTitle className="text-base print:text-sm print:font-bold">Action Context</CardTitle>
                    </CardHeader>
                    <CardContent className="pt-6 space-y-4 font-sans text-sm">
                        <div className="flex justify-between items-center">
                            <span className="text-muted-foreground">Action Type</span>
                            <span className="font-semibold">{log.action.type}</span>
                        </div>
                        <div className="flex justify-between items-center">
                            <span className="text-muted-foreground">Execution Status</span>
                            <Badge variant={log.status === 'SUCCESS' ? 'default' : 'destructive'} className="text-[10px] print:bg-white print:text-black print:border print:border-black">
                                {log.status}
                            </Badge>
                        </div>
                        <div className="space-y-1">
                            <span className="text-muted-foreground">Description</span>
                            <p className="leading-relaxed font-medium">{log.action.description}</p>
                        </div>
                    </CardContent>
                </Card>
            </div>

            {/* Raw Metadata Card */}
            <Card className="overflow-hidden border-zinc-200 dark:border-zinc-800 print:print-card">
                <CardHeader className="bg-muted/30 pb-3 flex items-center justify-between flex-row print:bg-zinc-50 print:border-b">
                    <div className="flex items-center gap-2">
                        <FileJson className="w-4 h-4 text-primary print:text-black" />
                        <CardTitle className="text-base print:text-sm print:font-bold">Raw System Snapshot</CardTitle>
                    </div>
                </CardHeader>
                <CardContent className="pt-6">
                    <pre className="p-4 rounded-xl bg-zinc-950 text-zinc-300 font-mono text-xs overflow-x-auto border border-zinc-800 print:bg-zinc-50 print:text-zinc-900 print:border-zinc-200">
                        {JSON.stringify(log, null, 2)}
                    </pre>
                </CardContent>
            </Card>

            <div className="bg-green-50 dark:bg-green-950/20 border border-green-200 dark:border-green-900/50 p-4 rounded-xl flex items-center gap-3 print:bg-white print:border-zinc-200 print:text-zinc-900">
                <ShieldAlert className="w-5 h-5 text-green-600 print:text-black" />
                <p className="text-sm text-green-700 dark:text-green-400 font-medium print:text-xs">
                    This log entry is read-only and immutable in compliance with SOC 2 integrity requirements. Authenticity verified by Bized Security Engine.
                </p>
            </div>
        </div>
    )
}
